version: '3.8'

services:
  servidor-web:
    image: nginx:alpine
    container_name: meu-site-nginx
    ports:
      - "9000:80" # A porta 8080 é a que acessamos no navegador localmente
    restart: always

#Alterações da Terra-52 -- 
